[phases.setup]
nixPkgs = ["nodejs", "yarn", "bash"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = [
  "bash ./railway-prebuild.sh",
  "NODE_OPTIONS=\"--no-deprecation\" yarn build --no-lint"
]

[start]
cmd = "NODE_OPTIONS=\"--no-deprecation\" yarn start"
