[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "NODE_OPTIONS=\"--no-deprecation\" npm run build"
]

[start]
cmd = "NODE_OPTIONS=\"--no-deprecation\" npm run start"
