[build]
builder = "DOCKERFILE"
dockerfilePath = "src/workers/py-worker/Dockerfile"
buildCommand = ""

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
# No healthcheck for worker services
healthcheckEnabled = false

[service.python-worker]
name = "Python Worker"
rootDirectory = "src/workers/py-worker"
