[build]
builder = "nixpacks"
buildCommand = "bash ./railway-prebuild.sh && NODE_OPTIONS=\"--no-deprecation\" yarn build --no-lint"
watchPatterns = ["src/**", "public/**"]

[deploy]
startCommand = "NODE_OPTIONS=\"--no-deprecation\" yarn start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[nixpacks]
pkgs = ["nodejs", "yarn", "bash"]
