[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools", "python310Packages.wheel", "bash"]

[phases.install]
# Execute build script to force a clean build
cmds = [
  "chmod +x build.sh",
  "./build.sh"
]

[start]
cmd = "python main.py"
